
public class blackbox extends loadrunner {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
/*blackbox black=new blackbox();
black.test();
black.testcases();
selenium sell=new selenium();
sell.testcases();*/
		loadrunner load=new blackbox();
		load.testcases();
		load=new selenium();
		load.testcases();
	}


@Override
public void testcases()
{
	System.out.println("GGenerated by user as well as automatic");
}
}
class selenium extends loadrunner{
	@Override
	public void testcases()
	{
		System.out.println("selenium auto");
	}
}
abstract class loadrunner
{
	public void test()
	{
		System.out.println("load capacity of site");
	}
	abstract public void testcases();
}